version: '3.8'

services:
  # Ton site web
  web:
    build: .
    container_name: mon-site-web
    ports:
      - "80:80"  # C'est cette ligne qui fait le lien avec ton navigateur

  # Le traducteur pour que Prometheus comprenne Nginx
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    command: -nginx.scrape-uri=http://web:80/stub_status
    depends_on:
      - web

  # Prometheus pour collecter
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # Grafana pour afficher
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin